version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: alexdhub/foodgram_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    image: alexdhub/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  gateway:
    image: nginx:1.19.3
    env_file: .env
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
