# Generated by Django 3.2.3 on 2023-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Введите навзание рецепта', max_length=200, verbose_name='Название рецепта'),
        ),
    ]
