# Generated by Django 3.2.3 on 2023-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Добавьте изображение готового блюда', upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
